source 'https://github.com/CocoaPods/Specs.git'
source 'https://bitbucket.org/yikesdev/cocoapod-spec-repo'
# platform :ios, '9.0'

def mp_pods


  # Pods for YikesEngineMP
  # Private
  pod 'YikesSharedModel', :path => '../YikesSharedModel'
  
  # Public
  pod 'AFNetworking', '~>2.X'
  #pod 'AFNetworking/UIKit+AFNetworking'
  pod 'AFNetworkActivityLogger', '~>2.0'
  pod 'Colours', '~>5.6'
  pod 'JSBadgeView', '~>1.4'
  pod 'Mantle', '~>2.0'
  pod 'MSWeakTimer', '~>1.1'
  pod 'SDiPhoneVersion', '~>1.1.2'
  pod 'SSKeychain', '~>1.2'
  pod 'SSZipArchive', '~>0.4'
  pod 'WYPopoverController', '~>0.3.8'
  pod 'UICountingLabel', '~>1.2'
  pod 'PNChart', '~>0.8'
  
end


target 'YikesEngineMP' do
use_frameworks!
mp_pods
end

target 'YikesEngineMPTests' do
	use_frameworks!
	pod 'YikesEngineMP', :path => '../YikesEngineMP'
end