source 'https://github.com/CocoaPods/Specs.git'
source 'https://bitbucket.org/yikesdev/cocoapod-spec-repo'
# platform :ios, '9.0'

target 'YikesEngine' do

  # Pods for YikesEngine
  pod 'YikesEngineMP', :path => '../yikesenginemp'

use_frameworks!
  pod 'YikesEngineSP'#, :path => '../yikesengine'
  pod 'YikesSharedModel'#, :path => '../yikessharedmodel'
end

target 'YikesGenericEngine' do
  use_frameworks!
  pod 'YikesEngineSP'#, :path=> '../yikesengine'
  pod 'YikesEngineMP'#, :path=> '../yikesenginemp'
end

target 'YikesEngineTests' do
  use_frameworks!
  pod 'YikesGenericEngine'#, :path => '../yikesgenericengine'
end
